# This file was generated by GoReleaser. DO NOT EDIT.
cask "headroom" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/headroom"]
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "646f3ec012c2fcd1cd2991185af1a1677044fcb90dae26e668929823a9ee51b8"
      url "https://github.com/blacktop/headroom/releases/download/v#{version}/headroom_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "38266893dddd7e95d0a45a44edc086c88135d44be79f308e3e2f21b7678850de"
      url "https://github.com/blacktop/headroom/releases/download/v#{version}/headroom_#{version}_Darwin_x86_64.tar.gz"
    end
  end

  name "headroom"
  desc "Read-only macOS worker admission check"
  homepage "https://github.com/blacktop/headroom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "headroom"

  # No zap stanza required
end
