# This file was generated by GoReleaser. DO NOT EDIT.
cask "headroom" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/headroom"]
    end
  end

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "dcf056fd39699c902816466bef4f5b166b59131ca572bc3e574294d3a8ec3a48"
      url "https://github.com/blacktop/headroom/releases/download/v#{version}/headroom_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "464ade4cdb8a9fd52bc63b8142447311e772e23dc7bf8cd7bb0eb1728207c602"
      url "https://github.com/blacktop/headroom/releases/download/v#{version}/headroom_#{version}_Darwin_x86_64.tar.gz"
    end
  end

  name "headroom"
  desc "Read-only macOS worker admission check"
  homepage "https://github.com/blacktop/headroom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "headroom"

  # No zap stanza required
end
