# This file was generated by GoReleaser. DO NOT EDIT.
cask "ida-mcp" do
  name "ida-mcp"
  desc "Headless IDA Pro MCP Server for AI-powered binary analysis"
  homepage "https://github.com/blacktop/ida-mcp-rs"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ida-mcp"

  on_macos do
    on_arm do
      url "https://github.com/blacktop/ida-mcp-rs/releases/download/v#{version}/ida-mcp_#{version}_Darwin_arm64.tar.gz"
      sha256 "86c6e1761c813bbaa9fb61c707d156c2004a35a5ab9862d2c0b7c786ea750b9f"
    end
  end

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/**/ida-mcp").each do |f|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", f]
      end
    end
  end

  caveats do
    "ida-mcp requires IDA Pro 9.2+ to be installed."
  end

  # No zap stanza required
end
