# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipsw" do
  name "ipsw"
  desc "iOS/macOS Research Swiss Army Knife"
  homepage "https://github.com/blacktop/ipsw"
  version "3.1.643"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipsw"
  manpage "manpages/*"
  bash_completion "completions/ipsw/_bash"
  zsh_completion "completions/ipsw/_zsh"
  fish_completion "completions/ipsw/_fish"

  on_macos do
    on_intel do
      url "https://github.com/blacktop/ipsw/releases/download/v#{version}/ipsw_#{version}_macOS_x86_64_extras.tar.gz",
        verified: "github.com/blacktop/ipsw/releases/download"
      sha256 "942b694dd7c98fbb4a954a88d18df7e79361f24bc129c8f1371becd82c6a9a79"
    end
    on_arm do
      url "https://github.com/blacktop/ipsw/releases/download/v#{version}/ipsw_#{version}_macOS_arm64_extras.tar.gz",
        verified: "github.com/blacktop/ipsw/releases/download"
      sha256 "f8a80d46d644be90f921a9d5c74a164d3f4e87d5f926b378deadcdea7fa2b8b2"
    end
  end

  conflicts_with cask: [
      "ipsw-frida",
    ]

  # No zap stanza required
end
