# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipsw" do
  name "ipsw"
  desc "iOS/macOS Research Swiss Army Knife"
  homepage "https://github.com/blacktop/ipsw"
  version "3.1.652"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipsw"
  manpage "manpages/*"
  bash_completion "completions/ipsw/_bash"
  zsh_completion "completions/ipsw/_zsh"
  fish_completion "completions/ipsw/_fish"

  on_macos do
    on_intel do
      url "https://github.com/blacktop/ipsw/releases/download/v#{version}/ipsw_#{version}_macOS_x86_64_extras.tar.gz",
        verified: "github.com/blacktop/ipsw/releases/download"
      sha256 "f03876341402b0849c9d93e253b1c778a6f3ba297d5b69da86b9b9f78b8779ac"
    end
    on_arm do
      url "https://github.com/blacktop/ipsw/releases/download/v#{version}/ipsw_#{version}_macOS_arm64_extras.tar.gz",
        verified: "github.com/blacktop/ipsw/releases/download"
      sha256 "316446948eee16327ec70776b65f1f027048bef4ffc955626f9ac010c39fc313"
    end
  end

  conflicts_with cask: [
      "ipsw-frida",
    ]

  # No zap stanza required
end
