# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipsw" do
  name "ipsw"
  desc "iOS/macOS Research Swiss Army Knife"
  homepage "https://github.com/blacktop/ipsw"
  version "3.1.654"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipsw"
  manpage "manpages/ipsw.1.gz"
  bash_completion "completions/ipsw/_bash"
  zsh_completion "completions/ipsw/_zsh"
  fish_completion "completions/ipsw/_fish"

  on_macos do
    on_intel do
      url "https://github.com/blacktop/ipsw/releases/download/v#{version}/ipsw_#{version}_macOS_x86_64_extras.tar.gz",
        verified: "github.com/blacktop/ipsw/releases/download"
      sha256 "050ab3b041aa98559532ab63b6bd91083af80beb0b70a4b5ef5e2784fc61099e"
    end
    on_arm do
      url "https://github.com/blacktop/ipsw/releases/download/v#{version}/ipsw_#{version}_macOS_arm64_extras.tar.gz",
        verified: "github.com/blacktop/ipsw/releases/download"
      sha256 "a7c01872c751fd2dfe3c806ab401dffc61da7e2052f0ad2d4a188594c75f9411"
    end
  end

  conflicts_with cask: [
      "ipsw-frida",
    ]

  # No zap stanza required
end
