# This file was generated by GoReleaser. DO NOT EDIT.
cask "twit" do
  name "twit"
  desc "A beautiful TUI client for Twitter/X"
  homepage "https://github.com/blacktop/twit"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twit"

  on_macos do
    on_arm do
      url "https://github.com/blacktop/twit/releases/download/v#{version}/twit_#{version}_Darwin_arm64.tar.gz"
      sha256 "ee8d6b4ca819fd5f7854d7370dee1536948efdac731843aa98d0801c562385b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blacktop/twit/releases/download/v#{version}/twit_#{version}_Linux_x86_64.tar.gz"
      sha256 "2e46439bbc7c8f7b3153f52eac65e06df13e164e070da2e3af0934b59bed987c"
    end
    on_arm do
      url "https://github.com/blacktop/twit/releases/download/v#{version}/twit_#{version}_Linux_arm64.tar.gz"
      sha256 "d756646f3e296c0df155ec4d23ddeb1b2faf8efee73c0ae0e1ef8aa1a4e5f12e"
    end
  end

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/**/twit").each do |f|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", f]
      end
    end
  end

  # No zap stanza required
end
