# This file was generated by GoReleaser. DO NOT EDIT.
cask "twit" do
  name "twit"
  desc "A beautiful TUI client for Twitter/X"
  homepage "https://github.com/blacktop/twit"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twit"

  on_macos do
    on_arm do
      url "https://github.com/blacktop/twit/releases/download/v#{version}/twit_#{version}_Darwin_arm64.tar.gz"
      sha256 "368758733e12eda5e37c01d8f63c9cf7de6c8ce7099b64967132e0c7063f46ba"
    end
  end

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/**/twit").each do |f|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", f]
      end
    end
  end

  # No zap stanza required
end
