# This file was generated by GoReleaser. DO NOT EDIT.
cask "twit" do
  name "twit"
  desc "A beautiful TUI client for Twitter/X"
  homepage "https://github.com/blacktop/twit"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twit"

  on_macos do
    on_arm do
      url "https://github.com/blacktop/twit/releases/download/v#{version}/twit_#{version}_Darwin_arm64.tar.gz"
      sha256 "0a1ecd085d1abc393dcd08c04230fca717ef80d609304f61c738cc745c2dbe27"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blacktop/twit/releases/download/v#{version}/twit_#{version}_Linux_x86_64.tar.gz"
      sha256 "d2dbb6baf5d2ed4a3b7e6753a367fdeab739cecfd84e21e57b30af7781587a6e"
    end
    on_arm do
      url "https://github.com/blacktop/twit/releases/download/v#{version}/twit_#{version}_Linux_arm64.tar.gz"
      sha256 "a44efeb259007a094464ca9b87d7f9139ff9920a0dd6c339f13200707ea69445"
    end
  end

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/**/twit").each do |f|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", f]
      end
    end
  end

  # No zap stanza required
end
