# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 8sleep < Formula
  desc "Control 8sleep via CLI"
  homepage "https://github.com/blacktop/8sleep"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/8sleep/releases/download/v0.1.2/8sleep_0.1.2_macOS_x86_64.tar.gz"
      sha256 "e77d72d99c611882da21bf2912fbba3a865b2a6847bc7fff86c06d72410d5335"

      def install
        bin.install "8sleep"
        bash_completion.install "completions/_bash" => "8sleep"
        zsh_completion.install "completions/_zsh" => "_8sleep"
        fish_completion.install "completions/_fish" => "8sleep.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/8sleep/releases/download/v0.1.2/8sleep_0.1.2_macOS_arm64.tar.gz"
      sha256 "a9b94e4ce16423b884fcda556cec12a53eb91ddaf436b6ea1b69b6bfaf7f0d9d"

      def install
        bin.install "8sleep"
        bash_completion.install "completions/_bash" => "8sleep"
        zsh_completion.install "completions/_zsh" => "_8sleep"
        fish_completion.install "completions/_fish" => "8sleep.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/8sleep/releases/download/v0.1.2/8sleep_0.1.2_linux_x86_64.tar.gz"
      sha256 "bd95671666913db2f345fa6baa51a3e0fb115b46cc79dd24b84d1ae1f391a267"
      def install
        bin.install "8sleep"
        bash_completion.install "completions/_bash" => "8sleep"
        zsh_completion.install "completions/_zsh" => "_8sleep"
        fish_completion.install "completions/_fish" => "8sleep.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/8sleep/releases/download/v0.1.2/8sleep_0.1.2_linux_arm64.tar.gz"
      sha256 "79702be8d54012a2a1e5a590b78e2b86426f7d139458dfe7475fba0364841b3f"
      def install
        bin.install "8sleep"
        bash_completion.install "completions/_bash" => "8sleep"
        zsh_completion.install "completions/_zsh" => "_8sleep"
        fish_completion.install "completions/_fish" => "8sleep.fish"
      end
    end
  end

  service do
    run [opt_bin/"8sleep", "temp", "75F"]
    run_type :cron
    cron "0 23 * * *"
    log_path var/"log/8sleep.log"
    error_log_path var/"log/8sleep.err.log"
  end

  test do
    system "#{bin}/8sleep --help"
  end
end
