# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 8sleep < Formula
  desc "Control 8sleep via CLI"
  homepage "https://github.com/blacktop/8sleep"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/8sleep/releases/download/v0.1.1/8sleep_0.1.1_macOS_x86_64.tar.gz"
      sha256 "f8cc856a702bd819f6a98fe63e0f45e0241f4b59a29e5846b3c8882bcc317625"

      def install
        bin.install "8sleep"
        bash_completion.install "completions/_bash" => "8sleep"
        zsh_completion.install "completions/_zsh" => "_8sleep"
        fish_completion.install "completions/_fish" => "8sleep.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/8sleep/releases/download/v0.1.1/8sleep_0.1.1_macOS_arm64.tar.gz"
      sha256 "1251b5dad5406ad369d2748d467f2e3b9b38c4e500eb272c5840d392e09afa70"

      def install
        bin.install "8sleep"
        bash_completion.install "completions/_bash" => "8sleep"
        zsh_completion.install "completions/_zsh" => "_8sleep"
        fish_completion.install "completions/_fish" => "8sleep.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/8sleep/releases/download/v0.1.1/8sleep_0.1.1_linux_x86_64.tar.gz"
      sha256 "7b5f76d2bb2a85f0a6312451fcd958e3c2b9b688dcc8eb54998d8ff49a92c12d"
      def install
        bin.install "8sleep"
        bash_completion.install "completions/_bash" => "8sleep"
        zsh_completion.install "completions/_zsh" => "_8sleep"
        fish_completion.install "completions/_fish" => "8sleep.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/8sleep/releases/download/v0.1.1/8sleep_0.1.1_linux_arm64.tar.gz"
      sha256 "8db3fb98a1d087c300646958c731dfedab625d85fed84a6ddcfb4b5b401e86fb"
      def install
        bin.install "8sleep"
        bash_completion.install "completions/_bash" => "8sleep"
        zsh_completion.install "completions/_zsh" => "_8sleep"
        fish_completion.install "completions/_fish" => "8sleep.fish"
      end
    end
  end

  service do
    run [opt_bin/"8sleep", "temp", "75F"]
    run_type :cron
    cron "0 23 * * *"
    log_path var/"log/8sleep.log"
    error_log_path var/"log/8sleep.err.log"
  end

  test do
    system "#{bin}/8sleep --help"
  end
end
