# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apfs < Formula
  desc "APFS parser written in pure Go"
  homepage "https://github.com/blacktop/go-apfs"
  version "1.0.17"
  depends_on :macos

  on_macos do
    url "https://github.com/blacktop/go-apfs/releases/download/v1.0.17/apfs_1.0.17_macOS_universal.tar.gz"
    sha256 "1115b83d3c8719785e16d32cd19012d1ead73b2148f0d79764ff20489784bc79"

    def install
      bin.install "apfs"
      bash_completion.install "completions/_bash" => "apfs"
      zsh_completion.install "completions/_zsh" => "_apfs"
      fish_completion.install "completions/_fish" => "apfs.fish"
    end
  end

  test do
    system "#{bin}/apfs --version"
  end
end
