# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppIcon < Formula
  desc "Generate macOS App Icons"
  homepage "https://github.com/blacktop/app-icon"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/blacktop/app-icon/releases/download/v0.1.0/app-icon_0.1.0_macOS_universal.tar.gz"
    sha256 "2581be985ff9f5a787d458734dba3c2f8ac713fbadf52e57ef034445ce25909c"

    def install
      bin.install "app-icon"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/app-icon/releases/download/v0.1.0/app-icon_0.1.0_linux_arm64.tar.gz"
      sha256 "cfe85f82a9cda291dba6e5eabaca6584303677f34f306b8e7a05cd972d4091b0"

      def install
        bin.install "app-icon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/app-icon/releases/download/v0.1.0/app-icon_0.1.0_linux_x86_64.tar.gz"
      sha256 "76375286b05639180527b5d77ec84176334af2dd73096d4615e052f63a4c82c1"

      def install
        bin.install "app-icon"
      end
    end
  end

  test do
    system "#{bin}/app-icon --help"
  end
end
