# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BindiffRs < Formula
  desc "Rust bindiff wrapper"
  homepage "https://github.com/blacktop/bindiff-rs"
  version "0.1.6"
  license "MIT"

  on_macos do
    url "https://github.com/blacktop/bindiff-rs/releases/download/v0.1.6/bindiff-rs_0.1.6_macOS_universal.tar.gz"
    sha256 "91c0c6d64829363b315a0068fee434f5e7240993487d2eae474020bc51e5d2e0"

    def install
      bin.install "bindiff-rs"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/bindiff-rs/releases/download/v0.1.6/bindiff-rs_0.1.6_linux_arm64.tar.gz"
        sha256 "187f1d2f11bdecc0ae30cbc5693c4b71fc0a6e30d7deb0e44813f99084cb18c2"

        def install
          bin.install "bindiff-rs"
        end
      end
    end
  end
end
