# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BindiffRs < Formula
  desc "Rust bindiff wrapper"
  homepage "https://github.com/blacktop/bindiff-rs"
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/blacktop/bindiff-rs/releases/download/v0.1.1/bindiff-rs_0.1.1_macOS_universal.tar.gz"
    sha256 "f970373dc44185f2d071957b34a86b9744e332d7f7e897f3d483c17b96b88f1b"

    def install
      bin.install "bindiff-rs"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/bindiff-rs/releases/download/v0.1.1/bindiff-rs_0.1.1_linux_arm64.tar.gz"
        sha256 "1a3e308f9ce6b753fcb15260027f5f27ab6e1405b05efd2ca60c738febbb5b85"

        def install
          bin.install "bindiff-rs"
        end
      end
    end
  end
end
