# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BindiffRs < Formula
  desc "Rust bindiff wrapper"
  homepage "https://github.com/blacktop/bindiff-rs"
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/blacktop/bindiff-rs/releases/download/v0.1.1/bindiff-rs_Darwin_all.tar.gz"
    sha256 "55c6b5660c852a683978b31661a3df75433f5637c06549debbba53de2552dcd4"

    def install
      bin.install "bindiff-rs"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/bindiff-rs/releases/download/v0.1.1/bindiff-rs_Linux_arm64.tar.gz"
        sha256 "ff041e06265621422dc574f3d08ffdaaf9475048e6eeec40057b989daf480ee6"

        def install
          bin.install "bindiff-rs"
        end
      end
    end
  end
end
