# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BindiffRs < Formula
  desc "Rust bindiff wrapper"
  homepage "https://github.com/blacktop/bindiff-rs"
  version "0.1.4"
  license "MIT"

  on_macos do
    url "https://github.com/blacktop/bindiff-rs/releases/download/v0.1.4/bindiff-rs_0.1.4_macOS_universal.tar.gz"
    sha256 "f178d7f963ef24a1b76d4d7e1a48dff0ce6c6d493500001ac30e0e2086b2e36b"

    def install
      bin.install "bindiff-rs"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/bindiff-rs/releases/download/v0.1.4/bindiff-rs_0.1.4_linux_arm64.tar.gz"
        sha256 "fa804a90f866c299e75929906b627544c4eaceedfd03a61b4a107e0c3ce8e18c"

        def install
          bin.install "bindiff-rs"
        end
      end
    end
  end
end
