# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BottleBomb < Formula
  desc "Homebrew Bottle Downloader"
  homepage "https://github.com/blacktop/bottle-bomb"
  version "1.0.13"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/blacktop/bottle-bomb/releases/download/v1.0.13/bottle-bomb_1.0.13_macOS_x86_64.tar.gz"
      sha256 "4bdc7054701ba15a48074816d6e7f761c7a4f11a00b742f8827e0c5f19ec6ff7"

      def install
        bin.install "bb"
      end
    end
    on_arm do
      url "https://github.com/blacktop/bottle-bomb/releases/download/v1.0.13/bottle-bomb_1.0.13_macOS_arm64.tar.gz"
      sha256 "f12ead3d53a9578add7b3abbf873bef76275c46291026c57f13951e094b8bf60"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/bottle-bomb/releases/download/v1.0.13/bottle-bomb_1.0.13_linux_x86_64.tar.gz"
        sha256 "10cffa667ca5c06329dd1599f8e5056dd05132ea5298e17255889adc1a55f384"

        def install
          bin.install "bb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/bottle-bomb/releases/download/v1.0.13/bottle-bomb_1.0.13_linux_arm64.tar.gz"
        sha256 "016f884d04381eaa6548f9f3304bd03ddfe2b377dc0970692b94288dbc09c8da"

        def install
          bin.install "bb"
        end
      end
    end
  end

  test do
    system "#{bin}/bb --help"
  end
end
