# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BottleBomb < Formula
  desc "Homebrew Bottle Downloader"
  homepage "https://github.com/blacktop/bottle-bomb"
  version "1.0.11"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/blacktop/bottle-bomb/releases/download/v1.0.11/bottle-bomb_1.0.11_macOS_x86_64.tar.gz"
      sha256 "b72bc95f26ffaa33f43ff668be9543d12416013eb5fabcbb687b1a84a6ff177d"

      def install
        bin.install "bb"
      end
    end
    on_arm do
      url "https://github.com/blacktop/bottle-bomb/releases/download/v1.0.11/bottle-bomb_1.0.11_macOS_arm64.tar.gz"
      sha256 "7f9fcd34fc95986c9a8939fab9133d8fd4240148c081f4c62534c6c2e3a7d86e"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/bottle-bomb/releases/download/v1.0.11/bottle-bomb_1.0.11_linux_x86_64.tar.gz"
        sha256 "de65d0c740a632fbb31cb703e20605af0af010dea0b4ed20a94c308de0f2efef"

        def install
          bin.install "bb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/bottle-bomb/releases/download/v1.0.11/bottle-bomb_1.0.11_linux_arm64.tar.gz"
        sha256 "db7b6ddd2e8d4b6f550d14f23469181d84d11e338343f8e2a146c97293f38cd3"

        def install
          bin.install "bb"
        end
      end
    end
  end

  test do
    system "#{bin}/bb --help"
  end
end
