# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clim8 < Formula
  desc "Control Eight Sleep via CLI"
  homepage "https://github.com/blacktop/clim8"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.5/clim8_0.1.5_macOS_x86_64.tar.gz"
      sha256 "3f38b37213052aa9363d588ffbec93869008bc9fa61f5ec1a090cf902875d770"

      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.5/clim8_0.1.5_macOS_arm64.tar.gz"
      sha256 "7e64a354a804b66f374fe12feae492d0883f46597d2da49c153cb969a1ef3b4b"

      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.5/clim8_0.1.5_linux_x86_64.tar.gz"
      sha256 "3a6e77c2ff4787ed8c190b987d9ca331d72d0eaa56d418c33bfad20955784681"
      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.5/clim8_0.1.5_linux_arm64.tar.gz"
      sha256 "9f318d82f61078a605943df2a5baed70a34c96467e8a480ac5ef3442d935881a"
      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
  end

  service do
    run [opt_bin/"clim8", "temp", "75F"]
    run_type :cron
    cron "0 23 * * *"
    log_path var/"log/clim8.log"
    error_log_path var/"log/clim8.err.log"
  end

  test do
    system "#{bin}/clim8 --help"
  end
end
