# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clim8 < Formula
  desc "Control Eight Sleep via CLI"
  homepage "https://github.com/blacktop/clim8"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.9/clim8_0.1.9_macOS_x86_64.tar.gz"
      sha256 "ef088aca73ea01ab10f1da5397a43cd8ddb7a8bedb6987effd4fbc192ac8b53e"

      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.9/clim8_0.1.9_macOS_arm64.tar.gz"
      sha256 "0083b768e84139e56d586d611d92bc728c62a35bb5c0d1a1c536713d2b03d998"

      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.9/clim8_0.1.9_linux_x86_64.tar.gz"
      sha256 "564be3b49a9a4b09baf0b8fffa3d2949b56fa8163878d96ffa601868345c7abf"
      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.9/clim8_0.1.9_linux_arm64.tar.gz"
      sha256 "d5a91fe41c97a08f6295b40e007b9c4e939e7533ebbd7d0ff326d47d92c5d8a1"
      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
  end

  service do
    run [opt_bin/"clim8", "temp"]
    run_type :cron
    cron "0 23 * * *"
    log_path var/"log/clim8.log"
    error_log_path var/"log/clim8.err.log"
  end

  test do
    system "#{bin}/clim8 --help"
  end
end
