# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clim8 < Formula
  desc "Control Eight Sleep via CLI"
  homepage "https://github.com/blacktop/clim8"
  version "0.1.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.15/clim8_0.1.15_macOS_x86_64.tar.gz"
      sha256 "dbe9c3ffe98e587920a09b340aee1e24b8cb9060f311908397d444d5e2d1fee9"

      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.15/clim8_0.1.15_macOS_arm64.tar.gz"
      sha256 "1f8774d10cd89e9ac00fd4e53a4be8c1cf30aabd95574b4efb2fafe1bc469c22"

      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.15/clim8_0.1.15_linux_x86_64.tar.gz"
      sha256 "23edd8e280fd2ee1b547822f854996828677ae31b0ed60f9d2f2b81f85964dca"
      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/clim8/releases/download/v0.1.15/clim8_0.1.15_linux_arm64.tar.gz"
      sha256 "f7d3f2b9db4660992b36965d686784895e5f483e4b1e406899f7aaab1974ea90"
      def install
        bin.install "clim8"
        bash_completion.install "completions/_bash" => "clim8"
        zsh_completion.install "completions/_zsh" => "_clim8"
        fish_completion.install "completions/_fish" => "clim8.fish"
      end
    end
  end

  service do
    run [opt_bin/"clim8", "daemon"]
    keep_alive true
    log_path var/"log/clim8.log"
    error_log_path var/"log/clim8.log"
  end

  test do
    system "#{bin}/clim8 --help"
  end
end
