# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Disass < Formula
  desc "MachO ARMv9-a Disassembler"
  homepage "https://github.com/blacktop/arm64-cgo"
  version "1.0.55"
  depends_on :macos

  on_macos do
    url "https://github.com/blacktop/arm64-cgo/releases/download/v1.0.55/disass_1.0.55_macOS_universal.tar.gz"
    sha256 "9fcab8c14a31fff40c17ac8dece10c755c01e0889f3788b87a6e0d16d7df3b6b"

    def install
      bin.install "disass"
      bash_completion.install "completions/_bash" => "disass"
      zsh_completion.install "completions/_zsh" => "_disass"
      fish_completion.install "completions/_fish" => "disass.fish"
    end
  end

  depends_on "bat" => :optional

  test do
    system "#{bin}/disass --version"
  end
end
