# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fluxy < Formula
  desc "FLUX image generator TUI"
  homepage "https://github.com/blacktop/fluxy"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/blacktop/fluxy/releases/download/v0.1.6/fluxy_0.1.6_macOS_x86_64.tar.gz"
      sha256 "48c814839b5cfe8f766b041571fc8395d66e7e05de4dc2174cf99ca41da46952"

      def install
        bin.install "fluxy"
      end
    end
    on_arm do
      url "https://github.com/blacktop/fluxy/releases/download/v0.1.6/fluxy_0.1.6_macOS_arm64.tar.gz"
      sha256 "b7da78034724a545773526c7740435330a5f6da81141d8b7bfa91c7664fbf44d"

      def install
        bin.install "fluxy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/fluxy/releases/download/v0.1.6/fluxy_0.1.6_linux_x86_64.tar.gz"
        sha256 "092debd5abbc3e6895d364cb6d07854c1ce19dd6f41f826ccd967c2baee22ca7"

        def install
          bin.install "fluxy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/fluxy/releases/download/v0.1.6/fluxy_0.1.6_linux_arm64.tar.gz"
        sha256 "d2c5a32ecb71045e68dc16740ea52747c97407cdfce048561ec2aa5d3791dfa3"

        def install
          bin.install "fluxy"
        end
      end
    end
  end

  test do
    system "#{bin}/fluxy --help"
  end
end
