# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fluxy < Formula
  desc "FLUX image generator TUI"
  homepage "https://github.com/blacktop/fluxy"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/blacktop/fluxy/releases/download/v0.1.8/fluxy_0.1.8_macOS_x86_64.tar.gz"
      sha256 "1582683527e5e005aea387103ee05f590b46044a45fac01eb2b083595be9ae17"

      def install
        bin.install "fluxy"
      end
    end
    on_arm do
      url "https://github.com/blacktop/fluxy/releases/download/v0.1.8/fluxy_0.1.8_macOS_arm64.tar.gz"
      sha256 "4b8e0bf1a841570d124246d50c496e14ff509f7db8210f5357690a7ea205779d"

      def install
        bin.install "fluxy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/fluxy/releases/download/v0.1.8/fluxy_0.1.8_linux_x86_64.tar.gz"
        sha256 "9c325bac62381d0304ab4c626e102124c520d757421b9bc23d5a1589c1cb4f1b"

        def install
          bin.install "fluxy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/fluxy/releases/download/v0.1.8/fluxy_0.1.8_linux_arm64.tar.gz"
        sha256 "a3ac3a5fc772ce1cf94a2e77cf7616eab3b0dc5e1cc88c2a5b4d59658f93959f"

        def install
          bin.install "fluxy"
        end
      end
    end
  end

  test do
    system "#{bin}/fluxy --help"
  end
end
