# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fluxy < Formula
  desc "FLUX image generator TUI"
  homepage "https://github.com/blacktop/fluxy"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/blacktop/fluxy/releases/download/v0.1.7/fluxy_0.1.7_macOS_x86_64.tar.gz"
      sha256 "a98c9258829035b164985cdb6eb8e922fc820f1c8281cb41343cc0fe01f7ae44"

      def install
        bin.install "fluxy"
      end
    end
    on_arm do
      url "https://github.com/blacktop/fluxy/releases/download/v0.1.7/fluxy_0.1.7_macOS_arm64.tar.gz"
      sha256 "c4484cd9d03b0c6566f30ec334a8eb6add9ad61cc880c7d8c7e9f013ffe11e2a"

      def install
        bin.install "fluxy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/fluxy/releases/download/v0.1.7/fluxy_0.1.7_linux_x86_64.tar.gz"
        sha256 "5b170f60e9fe5266b8861c1728d3c76362030b2bb0947c4809a962f2dfd38715"

        def install
          bin.install "fluxy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/fluxy/releases/download/v0.1.7/fluxy_0.1.7_linux_arm64.tar.gz"
        sha256 "fc73f73d282abec8592fe7dfb22bf7c384948c51e3affe79ad3fdc23f7d96f9b"

        def install
          bin.install "fluxy"
        end
      end
    end
  end

  test do
    system "#{bin}/fluxy --help"
  end
end
