# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFoundationmodels < Formula
  desc "Lightweight Go package for on-device AI text generation using macOS 26 Tahoe's Foundation Models framework."
  homepage "https://github.com/blacktop/go-foundationmodels"
  version "0.1.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/blacktop/go-foundationmodels/releases/download/v0.1.4/go-foundationmodels_0.1.4_macOS_arm64.tar.gz"
    sha256 "4f4b438cdd08709ba2396cb40013ae6d72dbb8fbd45e9f3b7938fb6c4d9d60db"

    def install
      bin.install "found"
      bash_completion.install "completions/_bash" => "found"
      zsh_completion.install "completions/_zsh" => "_found"
      fish_completion.install "completions/_fish" => "found.fish"
    end
  end

  test do
    system "#{bin}/found --help"
  end
end
