# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFoundationmodels < Formula
  desc "Lightweight Go package for on-device AI text generation using macOS 26 Tahoe's Foundation Models framework."
  homepage "https://github.com/blacktop/go-foundationmodels"
  version "0.1.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/blacktop/go-foundationmodels/releases/download/v0.1.3/go-foundationmodels_0.1.3_macOS_arm64.tar.gz"
    sha256 "0a2ea0c8b2cb5b6cba45a58ef42653fa90d03f6d568b3c01974863e2a1da0a7e"

    def install
      bin.install "found"
      bash_completion.install "completions/_bash" => "found"
      zsh_completion.install "completions/_zsh" => "_found"
      fish_completion.install "completions/_fish" => "found.fish"
    end
  end

  test do
    system "#{bin}/found --help"
  end
end
