# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGitfamous < Formula
  desc "Github Event Tracker TUI"
  homepage "https://github.com/blacktop/go-gitfamous"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/go-gitfamous/releases/download/v0.1.8/go-gitfamous_0.1.8_macOS_x86_64.tar.gz"
      sha256 "83f183e6687c79ae7cedf3d197aeaad7832f8c9f2cdfdbf62dd66d47a2d58a72"

      def install
        bin.install "gitfamous"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/go-gitfamous/releases/download/v0.1.8/go-gitfamous_0.1.8_macOS_arm64.tar.gz"
      sha256 "df144c6dead2403bdcea403928f86058237998902f325d268d364528fb825142"

      def install
        bin.install "gitfamous"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/go-gitfamous/releases/download/v0.1.8/go-gitfamous_0.1.8_linux_x86_64.tar.gz"
      sha256 "6a576d373f673656da20ca480863bcef116327316690cf90c1e347d50908d516"
      def install
        bin.install "gitfamous"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/go-gitfamous/releases/download/v0.1.8/go-gitfamous_0.1.8_linux_arm64.tar.gz"
      sha256 "8e8cc7dd10b0c537d1d732a919189da41371297dbc61be8d0e70614c8ad11717"
      def install
        bin.install "gitfamous"
      end
    end
  end

  test do
    system "#{bin}/gitfamous --help"
  end
end
