# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGitfamous < Formula
  desc "Github Event Tracker TUI"
  homepage "https://github.com/blacktop/go-gitfamous"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/blacktop/go-gitfamous/releases/download/v0.1.6/go-gitfamous_0.1.6_macOS_x86_64.tar.gz"
      sha256 "22191e906b78227d1edad3b6037928eab825488a843d0e786324c755c445dab1"

      def install
        bin.install "gitfamous"
      end
    end
    on_arm do
      url "https://github.com/blacktop/go-gitfamous/releases/download/v0.1.6/go-gitfamous_0.1.6_macOS_arm64.tar.gz"
      sha256 "fcca24ee000218b094f55078ea6c7f93d0bfa754cf29d26b951c0debfbe61bb9"

      def install
        bin.install "gitfamous"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/go-gitfamous/releases/download/v0.1.6/go-gitfamous_0.1.6_linux_x86_64.tar.gz"
        sha256 "1eba3cac65bd93d41ae4d9dc1d7699e85b50fd81f86d9de9d2c5d44b9c77fb52"

        def install
          bin.install "gitfamous"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blacktop/go-gitfamous/releases/download/v0.1.6/go-gitfamous_0.1.6_linux_arm64.tar.gz"
        sha256 "9581f1e04f74f7801ce294499b97fa9233b633feaecc4353df5f77c640bc0d09"

        def install
          bin.install "gitfamous"
        end
      end
    end
  end

  test do
    system "#{bin}/gitfamous --help"
  end
end
