# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoHypervisor < Formula
  desc "Apple Hypervisor.framework Util"
  homepage "https://github.com/blacktop/hv"
  version "1.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/blacktop/go-hypervisor/releases/download/v1.0.1/go-hypervisor_1.0.1_macOS_arm64.tar.gz"
    sha256 "48c5c8e1ecfb8fcae4efcb5d10a0af21c50b2aa8722163be76d3c57caab683ee"

    def install
      bin.install "hv"
      bash_completion.install "completions/_bash" => "hv"
      zsh_completion.install "completions/_zsh" => "_TEMPLATE"
      fish_completion.install "completions/_fish" => "hv.fish"
    end
  end

  test do
    system "#{bin}/hv --help"
  end
end
