# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoHypervisor < Formula
  desc "Apple Hypervisor.framework Util"
  homepage "https://github.com/blacktop/hv"
  version "1.0.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/blacktop/go-hypervisor/releases/download/v1.0.2/go-hypervisor_1.0.2_macOS_arm64.tar.gz"
    sha256 "8be9e6f3af530b721a24cd1e89ccbc1935a0ed32679fb8d709f5143a62030877"

    def install
      bin.install "hv"
      bash_completion.install "completions/_bash" => "hv"
      zsh_completion.install "completions/_zsh" => "_TEMPLATE"
      fish_completion.install "completions/_fish" => "hv.fish"
    end
  end

  test do
    system "#{bin}/hv --help"
  end
end
