# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoHypervisor < Formula
  desc "Apple Hypervisor.framework Util"
  homepage "https://github.com/blacktop/hv"
  version "1.0.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/blacktop/go-hypervisor/releases/download/v1.0.3/go-hypervisor_1.0.3_macOS_arm64.tar.gz"
    sha256 "5878e13adddd349e7d75b5646d8aade1a864dfd964395cab8b00488b08b2d3dc"

    def install
      bin.install "hv"
      bash_completion.install "completions/_bash" => "hv"
      zsh_completion.install "completions/_zsh" => "_TEMPLATE"
      fish_completion.install "completions/_fish" => "hv.fish"
    end
  end

  test do
    system "#{bin}/hv --help"
  end
end
