# This file was generated by GoReleaser. DO NOT EDIT.
class Graboid < Formula
  desc "Clientless docker image downloader."
  homepage "https://github.com/blacktop/graboid"
  url "https://github.com/blacktop/graboid/releases/download/0.15.1/graboid_0.15.1_macOS_amd64.tar.gz"
  version "0.15.1"
  sha256 "879d3da6e6df9969c4e2659de3d1a4f479ae3a90d40ad164ea4ae1bcc3f45d75"

  def install
    bin.install "graboid"
  end

  test do
    system "#{bin}/graboid --version"
  end
end
