# This file was generated by GoReleaser. DO NOT EDIT.
class Graboid < Formula
  desc "Clientless docker image downloader."
  homepage "https://github.com/blacktop/graboid"
  version "0.15.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/blacktop/graboid/releases/download/0.15.3/graboid_0.15.3_macOS_amd64.tar.gz"
    sha256 "87a595b7a126b6fcd3911c26c14be5c6ccee04d85d6043bc90348ce01406ac04"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/graboid/releases/download/0.15.3/graboid_0.15.3_linux_amd64.tar.gz"
      sha256 "3c126443218dd927f8921650a077a6e145e307dc04608016a6c6bb9f4d8c2898"
    end
  end

  def install
    bin.install "graboid"
  end

  test do
    system "#{bin}/graboid --version"
  end
end
