# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lifx < Formula
  desc "LIFX Light TUI and MCP Server"
  homepage "https://github.com/blacktop/lifx"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.1/lifx_0.1.1_macOS_x86_64.tar.gz"
      sha256 "8e9fea5b8ddc5f9725f5ae57b833ee131889be0d76b1b97fde5bf49a6afcfa9a"

      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.1/lifx_0.1.1_macOS_arm64.tar.gz"
      sha256 "5d97423abf7c7b3cfc02498427c18ce8ba882295e855c7861f04425cbbe8f9c4"

      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.1/lifx_0.1.1_linux_x86_64.tar.gz"
      sha256 "1dd62ab0992159c0ab65bb5af55bc9a757ed5b99c8cca62e5ec59e4c6237e020"
      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.1/lifx_0.1.1_linux_arm64.tar.gz"
      sha256 "4fdeff456eed7afecca4bd3b6a1f8f2e7f26370f3f74e98a8852768092740df0"
      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
  end

  test do
    system "#{bin}/lifx --help"
  end
end
