# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lifx < Formula
  desc "LIFX Light TUI and MCP Server"
  homepage "https://github.com/blacktop/lifx"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.2/lifx_0.1.2_macOS_x86_64.tar.gz"
      sha256 "fa97510ba958b343b02fb2ca525eeaee882920361a997de2ebb866b9cf87021a"

      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.2/lifx_0.1.2_macOS_arm64.tar.gz"
      sha256 "c535c19018fafa3956712cc96859d45bd3c6e0e1784fe59271207ae2531c0b6f"

      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.2/lifx_0.1.2_linux_x86_64.tar.gz"
      sha256 "3c7687b1781f4620de95b7309e94533592825e13f4012192312d208483f67e48"
      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.2/lifx_0.1.2_linux_arm64.tar.gz"
      sha256 "175fbcd6dbb2f1361e1dd2676a8db9f6ce6b88ead400c307cb781164722d763e"
      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
  end

  test do
    system "#{bin}/lifx --help"
  end
end
