# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lifx < Formula
  desc "LIFX Light TUI and MCP Server"
  homepage "https://github.com/blacktop/lifx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.0/lifx_0.1.0_macOS_x86_64.tar.gz"
      sha256 "829f90680673a5e9a984e282a9346c41b07794998be2ebfb7bade922c625e547"

      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.0/lifx_0.1.0_macOS_arm64.tar.gz"
      sha256 "7525398cd30e8539edf500f55e702160b0e4458bd855ed67497534686c399622"

      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.0/lifx_0.1.0_linux_x86_64.tar.gz"
      sha256 "4be4f6c640aee6144eada790eebbf06f2b6d2f9f5b7ab2f2b19c05daf5ccd7ff"
      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/lifx/releases/download/v0.1.0/lifx_0.1.0_linux_arm64.tar.gz"
      sha256 "085e19bff76779fdcf4e717b2979e3587a90b32d65ab2a69edce8631e22e2bee"
      def install
        bin.install "lifx"
        bash_completion.install "completions/_bash" => "lifx"
        zsh_completion.install "completions/_zsh" => "_lifx"
        fish_completion.install "completions/_fish" => "lifx.fish"
      end
    end
  end

  test do
    system "#{bin}/lifx --help"
  end
end
