# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lporg < Formula
  desc "Organize Your macOS Launchpad Apps"
  homepage "https://github.com/blacktop/lporg"
  version "20.4.25"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/blacktop/lporg/releases/download/v20.4.25/lporg_20.4.25_macOS_universal.tar.gz"
    sha256 "3e088cb7354d8e0f429ebb07d25a9b7c405bfe026a09254371e727d6c7f13df6"

    def install
      bin.install "lporg"
      bash_completion.install "completions/_bash" => "lporg"
      zsh_completion.install "completions/_zsh" => "_lporg"
      fish_completion.install "completions/_fish" => "lporg.fish"
    end
  end

  test do
    system "#{bin}/lporg --version"
  end
end
