# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lporg < Formula
  desc "Organize Your macOS Launchpad Apps"
  homepage "https://github.com/blacktop/lporg"
  version "20.4.27"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/blacktop/lporg/releases/download/v20.4.27/lporg_20.4.27_macOS_universal.tar.gz"
    sha256 "cd38da60689641205be6f439bb8f27745f1bcbc194747b437232cff324e4a346"

    def install
      bin.install "lporg"
      bash_completion.install "completions/_bash" => "lporg"
      zsh_completion.install "completions/_zsh" => "_lporg"
      fish_completion.install "completions/_fish" => "lporg.fish"
    end
  end

  test do
    system "#{bin}/lporg --version"
  end
end
