# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lporg < Formula
  desc "Organize Your macOS Launchpad Apps"
  homepage "https://github.com/blacktop/lporg"
  version "20.4.6"
  depends_on :macos

  on_macos do
    url "https://github.com/blacktop/lporg/releases/download/v20.4.6/lporg_20.4.6_macOS_universal.tar.gz"
    sha256 "cade1f138ab750449c001ff03c61880a116103fa4f042445796676d94bda92c0"

    def install
      bin.install "lporg"
    end
  end

  test do
    system "#{bin}/lporg --version"
  end
end
