# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpTts < Formula
  desc "mcp-tts"
  homepage "https://github.com/blacktop/mcp-tts"
  version "0.1.17"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/blacktop/mcp-tts/releases/download/v0.1.17/mcp-tts_0.1.17_macOS_x86_64.tar.gz"
    sha256 "f87e2e40264de0517dc12ef78c4e82914979ee1c2c80128f6b93c9f7ed7336f6"

    def install
      bin.install "mcp-tts"
      bash_completion.install "completions/_bash" => "mcp-tts"
      zsh_completion.install "completions/_zsh" => "_mcp-tts"
      fish_completion.install "completions/_fish" => "mcp-tts.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/blacktop/mcp-tts/releases/download/v0.1.17/mcp-tts_0.1.17_macOS_arm64.tar.gz"
    sha256 "661bd08586d1ba69d23ca175925eae63825f39ae4b5dcdd9fc1ff132164469b1"

    def install
      bin.install "mcp-tts"
      bash_completion.install "completions/_bash" => "mcp-tts"
      zsh_completion.install "completions/_zsh" => "_mcp-tts"
      fish_completion.install "completions/_fish" => "mcp-tts.fish"
    end
  end

  test do
    system "#{bin}/mcp-tts --help"
  end
end
