# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpTts < Formula
  desc "mcp-tts"
  homepage "https://github.com/blacktop/mcp-tts"
  version "0.1.36"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/blacktop/mcp-tts/releases/download/v0.1.36/mcp-tts_0.1.36_macOS_x86_64.tar.gz"
    sha256 "97450ef063c0827e6ea336625a7d226fee707febe83e2edc2effcb11b0accce2"

    def install
      bin.install "mcp-tts"
      bash_completion.install "completions/_bash" => "mcp-tts"
      zsh_completion.install "completions/_zsh" => "_mcp-tts"
      fish_completion.install "completions/_fish" => "mcp-tts.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/blacktop/mcp-tts/releases/download/v0.1.36/mcp-tts_0.1.36_macOS_arm64.tar.gz"
    sha256 "f560f2181b9f7b9a1c5572c99db33c5d16cf05d4acd1eeb0901b8ab214564aa9"

    def install
      bin.install "mcp-tts"
      bash_completion.install "completions/_bash" => "mcp-tts"
      zsh_completion.install "completions/_zsh" => "_mcp-tts"
      fish_completion.install "completions/_fish" => "mcp-tts.fish"
    end
  end

  test do
    system "#{bin}/mcp-tts --help"
  end
end
