# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpSay < Formula
  desc "mcp-say"
  homepage "https://github.com/blacktop/mcp-say"
  version "0.1.11"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/blacktop/mcp-say/releases/download/v0.1.11/mcp-say_0.1.11_macOS_x86_64.tar.gz"
    sha256 "947fbd72eec4324bb91831fd1c9c47a42f655f1fa2298939e9255e60ad47ebbe"

    def install
      bin.install "mcp-say"
      bash_completion.install "completions/_bash" => "mcp-say"
      zsh_completion.install "completions/_zsh" => "_mcp-say"
      fish_completion.install "completions/_fish" => "mcp-say.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/blacktop/mcp-say/releases/download/v0.1.11/mcp-say_0.1.11_macOS_arm64.tar.gz"
    sha256 "7d95544db4ef994401230433ec5919030372486cfe212ae309bdddba5f8ea56b"

    def install
      bin.install "mcp-say"
      bash_completion.install "completions/_bash" => "mcp-say"
      zsh_completion.install "completions/_zsh" => "_mcp-say"
      fish_completion.install "completions/_fish" => "mcp-say.fish"
    end
  end

  test do
    system "#{bin}/mcp-say --help"
  end
end
