# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpSay < Formula
  desc "mcp-say"
  homepage "https://github.com/blacktop/mcp-say"
  version "0.1.9"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/blacktop/mcp-say/releases/download/v0.1.9/mcp-say_0.1.9_macOS_x86_64.tar.gz"
    sha256 "42525f1463941a1b605ea404c880ecc4a794d2bac39d8f5afb8ea34c32026d50"

    def install
      bin.install "mcp-say"
      bash_completion.install "completions/_bash" => "mcp-say"
      zsh_completion.install "completions/_zsh" => "_mcp-say"
      fish_completion.install "completions/_fish" => "mcp-say.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/blacktop/mcp-say/releases/download/v0.1.9/mcp-say_0.1.9_macOS_arm64.tar.gz"
    sha256 "c2ce46aa4c8463073bc4374b77b8eea90245d46f3b0c7635204fae7c442c59d6"

    def install
      bin.install "mcp-say"
      bash_completion.install "completions/_bash" => "mcp-say"
      zsh_completion.install "completions/_zsh" => "_mcp-say"
      fish_completion.install "completions/_fish" => "mcp-say.fish"
    end
  end

  test do
    system "#{bin}/mcp-say --help"
  end
end
