# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpTts < Formula
  desc "mcp-tts"
  homepage "https://github.com/blacktop/mcp-tts"
  version "0.1.44"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/blacktop/mcp-tts/releases/download/v0.1.44/mcp-tts_0.1.44_macOS_x86_64.tar.gz"
    sha256 "879f052f4cd2802d2e68d3748641aa7a95be2894abfa39dd727f3563378ee3a2"

    define_method(:install) do
      bin.install "mcp-tts"
      bash_completion.install "completions/_bash" => "mcp-tts"
      zsh_completion.install "completions/_zsh" => "_mcp-tts"
      fish_completion.install "completions/_fish" => "mcp-tts.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/blacktop/mcp-tts/releases/download/v0.1.44/mcp-tts_0.1.44_macOS_arm64.tar.gz"
    sha256 "24b7ee8805ff99b94fe81741445e6bb90250741ce778d89aef9b791c881740ca"

    define_method(:install) do
      bin.install "mcp-tts"
      bash_completion.install "completions/_bash" => "mcp-tts"
      zsh_completion.install "completions/_zsh" => "_mcp-tts"
      fish_completion.install "completions/_fish" => "mcp-tts.fish"
    end
  end

  test do
    system "#{bin}/mcp-tts --help"
  end
end
