# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpSay < Formula
  desc "mcp-say"
  homepage "https://github.com/blacktop/mcp-say"
  version "0.1.10"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/blacktop/mcp-say/releases/download/v0.1.10/mcp-say_0.1.10_macOS_x86_64.tar.gz"
    sha256 "d8247c140e56e942b1c360c74cea0ff582325b04845a6bb3aaa56bdb0a532dcd"

    def install
      bin.install "mcp-say"
      bash_completion.install "completions/_bash" => "mcp-say"
      zsh_completion.install "completions/_zsh" => "_mcp-say"
      fish_completion.install "completions/_fish" => "mcp-say.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/blacktop/mcp-say/releases/download/v0.1.10/mcp-say_0.1.10_macOS_arm64.tar.gz"
    sha256 "6fb7ec5ba8f96377d46becfdc7f8381fdaeede8c0ccfca65b335075e97b52a3e"

    def install
      bin.install "mcp-say"
      bash_completion.install "completions/_bash" => "mcp-say"
      zsh_completion.install "completions/_zsh" => "_mcp-say"
      fish_completion.install "completions/_fish" => "mcp-say.fish"
    end
  end

  test do
    system "#{bin}/mcp-say --help"
  end
end
