# This file was generated by GoReleaser. DO NOT EDIT.
class WaitForEs < Formula
  desc "Wait until Elasticsearch become available"
  homepage "https://github.com/blacktop/wait-for-es"
  url "https://github.com/blacktop/wait-for-es/releases/download/v0.1.2/wait-for-es_0.1.2_MacOS_64-bit.tar.gz"
  version "0.1.2"
  sha256 "c68f7f4785debe7e53efac6197ede529f95b1199e65f2a8a05233109fef1365d"

  def install
    bin.install "wait-for-es"
  end

  test do
    system "#{bin}/wait-for-es --version"
  end
end
