# This file was generated by GoReleaser. DO NOT EDIT.
class WaitForEs < Formula
  desc "Wait until Elasticsearch become available"
  homepage "https://github.com/blacktop/wait-for-es"
  url "https://github.com/blacktop/wait-for-es/releases/download/0.1.1/wait-for-es_0.1.1_Darwin_x86_64.tar.gz"
  version "0.1.1"
  sha256 "b4533894206e6b1f1e5af12c32d7e718143b0082c451cef9ae6bed96b010bf34"

  def install
    bin.install "wait-for-es"
  end

  test do
    system "#{bin}/wait-for-es --version"
  end
end
