# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xpost < Formula
  desc "Cross post to all socials at once from your terminal"
  homepage "https://github.com/blacktop/xpost"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.1/xpost_1.0.1_macOS_x86_64.tar.gz"
      sha256 "bf5a86854ced7c46ccbef86e48d2d83bd699d099fed61bd3fd1573f3e667633a"

      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.1/xpost_1.0.1_macOS_arm64.tar.gz"
      sha256 "d8c3120d87c63d2513f392a2c608f791c776d9dcbd0bf9e2171bf7a27ea00b8b"

      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.1/xpost_1.0.1_linux_x86_64.tar.gz"
      sha256 "4cee0dcb89df2f155b161a58485783aa8cb8e3260ebe5969df5e4abfe86445aa"
      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.1/xpost_1.0.1_linux_arm64.tar.gz"
      sha256 "5dba7cff42d58eb0d9bf1b0ea4ada3a698c93296a1916dd8139edf03f7264c4e"
      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
  end

  test do
    system "#{bin}/xpost --help"
  end
end
