# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xpost < Formula
  desc "Cross post to all socials at once from your terminal"
  homepage "https://github.com/blacktop/xpost"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.4/xpost_1.0.4_macOS_x86_64.tar.gz"
      sha256 "2a2bcb7ab9666a1a37dd6887a23b3a1d6d8f103e96d76fd0f60542a75ce321a1"

      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.4/xpost_1.0.4_macOS_arm64.tar.gz"
      sha256 "a87bd3d4e3a8bdb78fa1afad5aa83b2f9dee99b06ea917ad7781d60640773f51"

      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.4/xpost_1.0.4_linux_x86_64.tar.gz"
      sha256 "55dba722636b5a5efcf7ad1e96c8c81b719b5a80b14ca43c0e541830a24f4130"
      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.4/xpost_1.0.4_linux_arm64.tar.gz"
      sha256 "0a6606afbbb7c3413b215ad9611e2fb8a5fa625b132a947332709168885bf935"
      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
  end

  test do
    system "#{bin}/xpost --help"
  end
end
