# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xpost < Formula
  desc "Cross post to all socials at once from your terminal"
  homepage "https://github.com/blacktop/xpost"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.5/xpost_1.0.5_macOS_x86_64.tar.gz"
      sha256 "db4cf3493093391e379cb9f6f9369055996b8a34b236bb459fbf084618be1dfd"

      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.5/xpost_1.0.5_macOS_arm64.tar.gz"
      sha256 "1d18972c73b99b3aec1f0b9b0bb706752d587f9b4ba83a773c6c5c50fb711d22"

      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.5/xpost_1.0.5_linux_x86_64.tar.gz"
      sha256 "8a0f772767a037963bfbf2fe6c7adfaa411dd88a65aa791192e6c750149dffdf"
      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/xpost/releases/download/v1.0.5/xpost_1.0.5_linux_arm64.tar.gz"
      sha256 "9b546ea9649d243b84f5c4ea740212812e5b1dfc47c65d3c442c06371c5013da"
      def install
        bin.install "xpost"
        bash_completion.install "completions/_bash" => "xpost"
        zsh_completion.install "completions/_zsh" => "_xport"
        fish_completion.install "completions/_fish" => "xpost.fish"
      end
    end
  end

  test do
    system "#{bin}/xpost --help"
  end
end
